# .goreleaser.yml
builds:
  - binary: otpgateway
    main: ./cmd/otpgateway
    goos:
      - darwin
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64

before:
  hooks:
  - make build

archives:
  - format: tar.gz
    files:
      - static/smtp.tpl
      - config.toml.sample
      - smtp.prov
      - README.md
      - LICENSE
